<?php

/**
 * This code is part of the FileManager software (www.gerd-tentler.de/tools/filemanager), copyright by
 * Gerd Tentler. Obtain permission before selling this code or hosting it on a commercial website or
 * redistributing it over the Internet or in any other medium. In all cases copyright must remain intact.
 */

//========================================================================================================
// General
//========================================================================================================
  $msg['fileInfo']      = "Info do Arquivo";
  $msg['name']          = "Nome";
  $msg['size']          = "Tamanho";
  $msg['lastChange']    = "Última Mudança";
  $msg['owner']         = "Proprietário";
  $msg['group']         = "Grupo";
  $msg['other']         = "Outros";
  $msg['read']          = "Leitura";
  $msg['write']         = "Gravação";
  $msg['execute']       = "Executar";
  $msg['permissions']   = "Permissões";
  $msg['error']         = "ERRO";
  $msg['searchResult']  = "Search Result";

//========================================================================================================
// Commands
//========================================================================================================
  $msg['cmdReset']      = "Resetar";
  $msg['cmdSave']       = "Salvar";
  $msg['cmdViewList']   = "Ver Lista";
  $msg['cmdGetFile']    = "Carregar Arquivo";
  $msg['cmdRename']     = "Renomear";
  $msg['cmdDelete']     = "Apagar";
  $msg['cmdEdit']       = "Editar";
  $msg['cmdChangePerm'] = "Mudar Permissões";
  $msg['cmdFileInfo']   = "Ver Informaçõe do Arquivo";
  $msg['cmdUploadFile'] = "Upload Arquivo";
  $msg['cmdChangeDir']  = "Mudar Diretório";
  $msg['cmdParentDir']  = "Diretório Parente";
  $msg['cmdNewDir']     = "Novo Diretório";
  $msg['cmdSortAsc']    = "Colocar em Ordem Ascendente";
  $msg['cmdSortDesc']   = "Colocar em Odem Descendente";
  $msg['cmdDetails']    = "View Details";
  $msg['cmdIcons']      = "View Icons";
  $msg['cmdSearch']     = "Search";
  $msg['cmdGoBack']     = "Go Back";
  $msg['cmdRefresh']    = "Refresh";
  $msg['cmdLogin']		  = "Login";

//========================================================================================================
// Error Messages
//========================================================================================================
  $msg['errPermChange'] = "Não Foi Possível Mudar as Permissões";
  $msg['errDirNew']     = "Erro ao Criar";
  $msg['errOpen']       = "Erro ao Abrir";
  $msg['errSave']       = "Erro ao Salvar";
  $msg['errDelete']     = "Erro ao Apagar";
  $msg['errRename']     = "Erro ao Renomear";
  $msg['errDisabled']   = "Esta Função Foi Desabilitada";
  $msg['errConnect']    = "Sem Conexão ao Servidor FTP";
  $msg['errLogin']      = "Falha de Login";
  $msg['errAccess']     = "Access denied";

//========================================================================================================
// Other Messages
//========================================================================================================
  $msg['msgRemoveDir']  = "Remover Este Diretório Permanentemente?";
  $msg['msgDeleteFile'] = "Apagar Este Arquivo Permanentemente?";
  $msg['msgSaveFile']   = "Salvar Arquivo e sobrescrever o Existente?";

//========================================================================================================

?>