<?php

/**
 * This code is part of the FileManager software (www.gerd-tentler.de/tools/filemanager), copyright by
 * Gerd Tentler. Obtain permission before selling this code or hosting it on a commercial website or
 * redistributing it over the Internet or in any other medium. In all cases copyright must remain intact.
 */

//========================================================================================================
// General
//========================================================================================================
  $msg['fileInfo']      = "Info relatives au Fichier";
  $msg['name']          = "Nom";
  $msg['size']          = "Taille";
  $msg['lastChange']    = "Modification";
  $msg['owner']         = "Propriétaire";
  $msg['group']         = "Groupe";
  $msg['other']         = "Autres";
  $msg['read']          = "Lire";
  $msg['write']         = "Ecrire";
  $msg['execute']       = "Executer";
  $msg['permissions']   = "Autorisations";
  $msg['error']         = "ERREUR";
  $msg['searchResult']  = "Search Result";

//========================================================================================================
// Commands
//========================================================================================================
  $msg['cmdReset']      = "Annuler";
  $msg['cmdSave']       = "Enregistrer";
  $msg['cmdViewList']   = "Voir la Liste";
  $msg['cmdGetFile']    = "Obtenir le Fichier";
  $msg['cmdRename']     = "Renommer";
  $msg['cmdDelete']     = "Supprimer";
  $msg['cmdEdit']       = "Modifier";
  $msg['cmdChangePerm'] = "Modifier les Autorisations";
  $msg['cmdFileInfo']   = "Voir les Info relatives au Fichier";
  $msg['cmdUploadFile'] = "Envoyer un Fichier";
  $msg['cmdChangeDir']  = "Changer le Répertoire";
  $msg['cmdParentDir']  = "Répertoire Parent";
  $msg['cmdNewDir']     = "Nouveau Répertoire";
  $msg['cmdSortAsc']    = "Tri Croissant";
  $msg['cmdSortDesc']   = "Tri Décroissant";
  $msg['cmdDetails']    = "Vue Détaillée";
  $msg['cmdIcons']      = "Vue Icone";
  $msg['cmdSearch']     = "Recherche";
  $msg['cmdGoBack']     = "Retour en arrière";
  $msg['cmdRefresh']    = "Rafraîchir";
  $msg['cmdLogin']		  = "Login";

//========================================================================================================
// Error Messages
//========================================================================================================
  $msg['errPermChange'] = "Impossible de changer les autorisations";
  $msg['errDirNew']     = "Erreur lors de la création";
  $msg['errOpen']       = "Erreur lors de l'ouverture";
  $msg['errSave']       = "Erreur lors de la sauvegarde";
  $msg['errDelete']     = "Erreur lors de la suppression";
  $msg['errRename']     = "Erreur lors du renommage";
  $msg['errDisabled']   = "Cette fonction a été désactivé";
  $msg['errConnect']    = "Pas de connexion au serveur FTP";
  $msg['errLogin']      = "Échec de la connexion";
  $msg['errAccess']     = "Accès refusé";

//========================================================================================================
// Other Messages
//========================================================================================================
  $msg['msgRemoveDir']  = "Supprimer ce répertoire de manière irréversible?";
  $msg['msgDeleteFile'] = "Supprimer ce dossier de manière irréversible?";
  $msg['msgSaveFile']   = "Enregistrer le fichier et écraser existant?";

//========================================================================================================

?>