<?php

/**
 * This code is part of the FileManager software (www.gerd-tentler.de/tools/filemanager), copyright by
 * Gerd Tentler. Obtain permission before selling this code or hosting it on a commercial website or
 * redistributing it over the Internet or in any other medium. In all cases copyright must remain intact.
 */

// encoding: iso-8859-2

//========================================================================================================
// General
//========================================================================================================
  $msg['fileInfo']      = "Informace o souboru";
  $msg['name']          = "Název";
  $msg['size']          = "Velikost";
  $msg['lastChange']    = "Zmìnìno";
  $msg['owner']         = "Vlastník";
  $msg['group']         = "Skupina";
  $msg['other']         = "Ostatní";
  $msg['read']          = "Ètení";
  $msg['write']         = "Zápis";
  $msg['execute']       = "Spu¹tìní";
  $msg['permissions']   = "Oprávnìní";
  $msg['error']         = "Chyba";
  $msg['searchResult']  = "Výsledky vyhledávání";

//========================================================================================================
// Commands
//========================================================================================================
  $msg['cmdReset']      = "Storno";
  $msg['cmdSave']       = "Ulo¾it";
  $msg['cmdViewList']   = "Zobrazit výpis";
  $msg['cmdGetFile']    = "Stáhnout soubor";
  $msg['cmdRename']     = "Pøejmenovat";
  $msg['cmdDelete']     = "Smazat";
  $msg['cmdEdit']       = "Upravit";
  $msg['cmdChangePerm'] = "Zmìnit pøístupová práva";
  $msg['cmdFileInfo']   = "Zobrazit informace o souboru";
  $msg['cmdUploadFile'] = "Nahrát soubor";
  $msg['cmdChangeDir']  = "Zmìnit slo¾ku";
  $msg['cmdParentDir']  = "Nadøazená slo¾ka";
  $msg['cmdNewDir']     = "Nová slo¾ka";
  $msg['cmdSortAsc']    = "Øadit vzestupnì";
  $msg['cmdSortDesc']   = "Øadit sestupnì";
  $msg['cmdDetails']    = "Zobrazit detaily";
  $msg['cmdIcons']      = "Zobrazit náhledy";
  $msg['cmdSearch']     = "Vyhledávání";
  $msg['cmdGoBack']     = "Zpìt";
  $msg['cmdRefresh']    = "Obnovit";
  $msg['cmdLogin']		  = "Login";

//========================================================================================================
// Error Messages
//========================================================================================================
  $msg['errPermChange'] = "Zmìna pøístupových práv se nezdaøila";
  $msg['errDirNew']     = "Chyba pøi vytváøení";
  $msg['errOpen']       = "Chyba pøi otevírání";
  $msg['errSave']       = "Chyba pøi ukládání";
  $msg['errDelete']     = "Chyba pøi mazání";
  $msg['errRename']     = "Chyba pøi pøejmenování";
  $msg['errDisabled']   = "Tato funkce je zakázána";
  $msg['errConnect']    = "Chybí pøipojení k FTP";
  $msg['errLogin']      = "Pøihlá¹ení selhalo";
  $msg['errAccess']     = "Nepovolený pøístup";

//========================================================================================================
// Other Messages
//========================================================================================================
  $msg['msgRemoveDir']  = "Chcete nenávratnì smazat tuto slo¾ku?";
  $msg['msgDeleteFile'] = "Chcete nenávratnì smazat tento soubor?";
  $msg['msgSaveFile']   = "Chcete soubor ulo¾it a existující pøepsat?";

//========================================================================================================
?>
