<?php

/**
 * This code is part of the FileManager software (www.gerd-tentler.de/tools/filemanager), copyright by
 * Gerd Tentler. Obtain permission before selling this code or hosting it on a commercial website or
 * redistributing it over the Internet or in any other medium. In all cases copyright must remain intact.
 */

//========================================================================================================
// General
//========================================================================================================
  $msg['fileInfo']      = "Filinformation";
  $msg['name']          = "Namn";
  $msg['size']          = "Storlek";
  $msg['lastChange']    = "Senast ändrad";
  $msg['owner']         = "Ägare";
  $msg['group']         = "Grupp";
  $msg['other']         = "Annat";
  $msg['read']          = "Read";
  $msg['write']         = "Write";
  $msg['execute']       = "Execute";
  $msg['permissions']   = "Rättigheter";
  $msg['error']         = "FEL";
  $msg['searchResult']  = "Search Result";

//========================================================================================================
// Commands
//========================================================================================================
  $msg['cmdReset']      = "Återställ";
  $msg['cmdSave']       = "Spara";
  $msg['cmdViewList']   = "Visa lista";
  $msg['cmdGetFile']    = "Hämta fil";
  $msg['cmdRename']     = "Byt namn";
  $msg['cmdDelete']     = "Radera";
  $msg['cmdEdit']       = "Ändra";
  $msg['cmdChangePerm'] = "Ändra rättigheter";
  $msg['cmdFileInfo']   = "Visa filinformation";
  $msg['cmdUploadFile'] = "Ladda upp fil";
  $msg['cmdChangeDir']  = "Byt mapp";
  $msg['cmdParentDir']  = "Byt mapp";
  $msg['cmdNewDir']     = "Ny mapp";
  $msg['cmdSortAsc']    = "Sortera stigande";
  $msg['cmdSortDesc']   = "Sortera fallande";
  $msg['cmdDetails']    = "View Details";
  $msg['cmdIcons']      = "View Icons";
  $msg['cmdSearch']     = "Search";
  $msg['cmdGoBack']     = "Go Back";
  $msg['cmdRefresh']    = "Refresh";
  $msg['cmdLogin']		  = "Login";

//========================================================================================================
// Error Messages
//========================================================================================================
  $msg['errPermChange'] = "Det gick inte att ändra rättigheter";
  $msg['errDirNew']     = "Det gick inte att skapa";
  $msg['errOpen']       = "Det gick inte att öppna";
  $msg['errSave']       = "Det gick inte att spara";
  $msg['errDelete']     = "Det gick inte att radera";
  $msg['errRename']     = "Det gick inte att byta namn";
  $msg['errDisabled']   = "Funktionen är avstängd";
  $msg['errConnect']    = "Ingen kontakt med FTP-server";
  $msg['errLogin']      = "Login misslyckades";
  $msg['errAccess']     = "Access denied";

//========================================================================================================
// Other Messages
//========================================================================================================
  $msg['msgRemoveDir']  = "Vill du verkligen radera mappen?";
  $msg['msgDeleteFile'] = "Vill du verkligen radera filen?";
  $msg['msgSaveFile']   = "Spara och skriv över existerande?";

//========================================================================================================

?>