<?php

/**
 * This code is part of the FileManager software (www.gerd-tentler.de/tools/filemanager), copyright by
 * Gerd Tentler. Obtain permission before selling this code or hosting it on a commercial website or
 * redistributing it over the Internet or in any other medium. In all cases copyright must remain intact.
 */
 
//========================================================================================================
// General
//========================================================================================================
  $msg['fileInfo']      = "Informacje o pliku";
  $msg['name']          = "Nazwa";
  $msg['size']          = "Rozmiar";
  $msg['lastChange']    = "Zmieniony";
  $msg['owner']         = "Wlasciciel";
  $msg['group']         = "Grupa";
  $msg['other']         = "Inne";
  $msg['read']          = "Odczyt";
  $msg['write']         = "Zapis";
  $msg['execute']       = "Wykonaj";
  $msg['permissions']   = "Uprawnienia";
  $msg['error']         = "BLAD";
  $msg['searchResult']  = "Wynik wyszukiwania";
 
//========================================================================================================
// Commands
//========================================================================================================
  $msg['cmdReset']      = "Resetuj";
  $msg['cmdSave']       = "Zapisz";
  $msg['cmdViewList']   = "Pokaz liste";
  $msg['cmdGetFile']    = "Pobierz plik";
  $msg['cmdRename']     = "Zmien nazwe";
  $msg['cmdDelete']     = "Usun";
  $msg['cmdEdit']       = "Edytuj";
  $msg['cmdChangePerm'] = "Zmien uprawnienia";
  $msg['cmdFileInfo']   = "Podglad pliku";
  $msg['cmdUploadFile'] = "Wgranie pliku";
  $msg['cmdChangeDir']  = "Zmien katalog";
  $msg['cmdParentDir']  = "Katalog nadrzedny";
  $msg['cmdNewDir']     = "Nowy katalog";
  $msg['cmdSortAsc']    = "Sortuj A-Z";
  $msg['cmdSortDesc']   = "Sortuj Z-A";
  $msg['cmdDetails']    = "Pokaz szczegףly";
  $msg['cmdIcons']      = "Pokaz ikony";
  $msg['cmdSearch']     = "Szukaj";
  $msg['cmdGoBack']     = "Powrףt";
  $msg['cmdRefresh']    = "Odswiez";
  $msg['cmdLogin']		  = "Login";
 
//========================================================================================================
// Error Messages
//========================================================================================================
  $msg['errPermChange'] = "Nie mozna zmienic uprawnien";
  $msg['errDirNew']     = "Blad podczas tworzenia pliku";
  $msg['errOpen']       = "Blad podczas otwierania pliku";
  $msg['errSave']       = "Blad podczas zapisywania pliku";
  $msg['errDelete']     = "Blad podczas usuwania pliku";
  $msg['errRename']     = "Blad podczas zmiany nazwy pliku";
  $msg['errDisabled']   = "Funkcja dezaktywowana";
  $msg['errConnect']    = "Brak polaczenia z serwerem FTP";
  $msg['errLogin']      = "Nie udalo sie zalogowac";
  $msg['errAccess']     = "Dostep zabroniony";
 
//========================================================================================================
// Other Messages
//========================================================================================================
  $msg['msgRemoveDir']  = "Na pewno usunac ten katalog?";
  $msg['msgDeleteFile'] = "Na pewno usunac ten plik?";
  $msg['msgSaveFile']   = "Na pewno nadpisac instniejacy plik?";
 
//========================================================================================================

?>