<?php

/**
 * This code is part of the FileManager software (www.gerd-tentler.de/tools/filemanager), copyright by
 * Gerd Tentler. Obtain permission before selling this code or hosting it on a commercial website or
 * redistributing it over the Internet or in any other medium. In all cases copyright must remain intact.
 */

//========================================================================================================
// General
//========================================================================================================
  $msg['fileInfo']      = "Info Fisier";
  $msg['name']          = "Nume";
  $msg['size']          = "Marime";
  $msg['lastChange']    = "Ultima Modificare";
  $msg['owner']         = "Propietar";
  $msg['group']         = "Grup";
  $msg['other']         = "Altii";
  $msg['read']          = "Citire";
  $msg['write']         = "Scriere";
  $msg['execute']       = "Executie";
  $msg['permissions']   = "Drepturi";
  $msg['error']         = "EROARE";
  $msg['searchResult']  = "Search Result";

//========================================================================================================
// Commands
//========================================================================================================
  $msg['cmdReset']      = "Reset";
  $msg['cmdSave']       = "Salvare";
  $msg['cmdViewList']   = "Vezi Lista";
  $msg['cmdGetFile']    = "Descarca";
  $msg['cmdRename']     = "Redenumeste";
  $msg['cmdDelete']     = "Sterge";
  $msg['cmdEdit']       = "Editeaza";
  $msg['cmdChangePerm'] = "Schimba Drepturile";
  $msg['cmdFileInfo']   = "Vezi Info Fisier";
  $msg['cmdUploadFile'] = "Pune Fisier";
  $msg['cmdChangeDir']  = "Schimba Directorul";
  $msg['cmdParentDir']  = "Schimba Directorul";
  $msg['cmdNewDir']     = "Director Nou";
  $msg['cmdSortAsc']    = "Sorteaza Ascendent";
  $msg['cmdSortDesc']   = "Sorteaza Descendent";
  $msg['cmdDetails']    = "View Details";
  $msg['cmdIcons']      = "View Icons";
  $msg['cmdSearch']     = "Search";
  $msg['cmdGoBack']     = "Go Back";
  $msg['cmdRefresh']    = "Refresh";
  $msg['cmdLogin']		  = "Login";

//========================================================================================================
// Error Messages
//========================================================================================================
  $msg['errPermChange'] = "Nu pot schimba drepturile";
  $msg['errDirNew']     = "Eroare la creare";
  $msg['errOpen']       = "Eroare la deschidere";
  $msg['errSave']       = "Eroare la salvare";
  $msg['errDelete']     = "Eroare la stergere";
  $msg['errRename']     = "Eroare la redenumire";
  $msg['errDisabled']   = "Aceasta functie a fost deactivata";
  $msg['errConnect']    = "Nu exista nici o conexiune catre serverul FTP";
  $msg['errLogin']      = "Autorizarea a esuat";
  $msg['errAccess']     = "Access denied";

//========================================================================================================
// Other Messages
//========================================================================================================
  $msg['msgRemoveDir']  = "Stergeti acest director permanent?";
  $msg['msgDeleteFile'] = "Stergeti acest fisier permanent?";
  $msg['msgSaveFile']   = "Salvati fisierul peste cel existent?";

//========================================================================================================

?>