<?php

/**
 * This code is part of the FileManager software (www.gerd-tentler.de/tools/filemanager), copyright by
 * Gerd Tentler. Obtain permission before selling this code or hosting it on a commercial website or
 * redistributing it over the Internet or in any other medium. In all cases copyright must remain intact.
 */

//========================================================================================================
// General
//========================================================================================================
  $msg['fileInfo']      = "Eigenschappen";
  $msg['name']          = "Naam";
  $msg['size']          = "Grootte";
  $msg['lastChange']    = "Gewijzigd op";
  $msg['owner']         = "Eigenaar";
  $msg['group']         = "Groep";
  $msg['other']         = "Overig";
  $msg['read']          = "Lezen";
  $msg['write']         = "Schrijven";
  $msg['execute']       = "Uitvoeren";
  $msg['permissions']   = "Bevoegdheden";
  $msg['error']         = "FOUT";
  $msg['searchResult']  = "Search Result";

//========================================================================================================
// Commands
//========================================================================================================
  $msg['cmdReset']      = "Reset";
  $msg['cmdSave']       = "Opslaan";
  $msg['cmdViewList']   = "Lijst tonen";
  $msg['cmdGetFile']    = "Bestand downloaden";
  $msg['cmdRename']     = "Naam wijzigen";
  $msg['cmdDelete']     = "Verwijderen";
  $msg['cmdEdit']       = "Bewerken";
  $msg['cmdChangePerm'] = "Bevoegdheden wijzigen";
  $msg['cmdFileInfo']   = "Eigenschappen tonen";
  $msg['cmdUploadFile'] = "Bestand uploaden";
  $msg['cmdChangeDir']  = "Map openen";
  $msg['cmdParentDir']  = "Bovenliggende map";
  $msg['cmdNewDir']     = "Nieuwe map";
  $msg['cmdSortAsc']    = "Sorteer oplopend";
  $msg['cmdSortDesc']   = "Sorteer aflopend";
  $msg['cmdDetails']    = "View Details";
  $msg['cmdIcons']      = "View Icons";
  $msg['cmdSearch']     = "Search";
  $msg['cmdGoBack']     = "Go Back";
  $msg['cmdRefresh']    = "Refresh";
  $msg['cmdLogin']		  = "Login";

//========================================================================================================
// Error Messages
//========================================================================================================
  $msg['errPermChange'] = "Bevoegdheden konden niet gewijzigd worden";
  $msg['errDirNew']     = "Fout tijdens aanmaken";
  $msg['errOpen']       = "Fout tijdens openen";
  $msg['errSave']       = "Fout tijdens opslaan";
  $msg['errDelete']     = "Fout tijdens verwijderen";
  $msg['errRename']     = "Fout tijdens naam wijzigen";
  $msg['errDisabled']   = "Deze functie is geblokkeerd";
  $msg['errConnect']    = "Geen verbinding met FTP server";
  $msg['errLogin']      = "Aanmelden mislukt";
  $msg['errAccess']     = "Access denied";

//========================================================================================================
// Other Messages
//========================================================================================================
  $msg['msgRemoveDir']  = "Weet u zeker dat u deze map definitief wilt verwijderen?";
  $msg['msgDeleteFile'] = "Weet u zeker dat u dit bestand definitief wilt verwijderen?";
  $msg['msgSaveFile']   = "Wilt u het bestaande bestand vervangen met dit bestand?";

//========================================================================================================

?>