<?php

/**
 * This code is part of the FileManager software (www.gerd-tentler.de/tools/filemanager), copyright by
 * Gerd Tentler. Obtain permission before selling this code or hosting it on a commercial website or
 * redistributing it over the Internet or in any other medium. In all cases copyright must remain intact.
 */

//========================================================================================================
// General
//========================================================================================================
  $msg['fileInfo']      = "הקובץ";
  $msg['name']          = "שם";
  $msg['size']          = "גודל";
  $msg['lastChange']    = "שינוי אחרון";
  $msg['owner']         = "בעלים";
  $msg['group']         = "קבוצה";
  $msg['other']         = "אחר";
  $msg['read']          = "קריאה";
  $msg['write']         = "כתיבה";
  $msg['execute']       = "הרצה";
  $msg['permissions']   = "הרשאות";
  $msg['error']         = "תקלה";
  $msg['searchResult']  = "תוצאות החיפוש";

//========================================================================================================
// Commands
//========================================================================================================
  $msg['cmdReset']      = "איפוס";
  $msg['cmdSave']       = "שמירה";
  $msg['cmdViewList']   = "רשימה";
  $msg['cmdGetFile']    = "הורדה";
  $msg['cmdRename']     = "שינוי שם";
  $msg['cmdDelete']     = "מחיקה";
  $msg['cmdEdit']       = "עריכה";
  $msg['cmdChangePerm'] = "שינוי הרשאות";
  $msg['cmdFileInfo']   = "הצג מידע";
  $msg['cmdUploadFile'] = "העלאת קובץ";
  $msg['cmdChangeDir']  = "עבור תיקיה";
  $msg['cmdParentDir']  = "תיקיה מעלה";
  $msg['cmdNewDir']     = "תיקיה חדשה";
  $msg['cmdSortAsc']    = "מיון עולה";
  $msg['cmdSortDesc']   = "מיון יורד";
  $msg['cmdDetails']    = "הצג פרטים";
  $msg['cmdIcons']      = "אייקונים";
  $msg['cmdSearch']     = "חיפוש";
  $msg['cmdGoBack']     = "חזרה";
  $msg['cmdRefresh']    = "רענון";
  $msg['cmdLogin']		  = "כניסה";

//========================================================================================================
// Error Messages
//========================================================================================================
  $msg['errPermChange'] = "אין אפשרות לשנות הרשאות";
  $msg['errDirNew']     = "תקלה ביצירה";
  $msg['errOpen']       = "תקלה בפתיחה";
  $msg['errSave']       = "תקלה בשמירה";
  $msg['errDelete']     = "תקלה במחיקה";
  $msg['errRename']     = "תקלה בשינוי שם";
  $msg['errDisabled']   = "(אי אפשר)";
  $msg['errConnect']    = "אין תקשורת עם FTP";
  $msg['errLogin']      = "שגיאה בכניסה";
  $msg['errAccess']     = "אין גישה";

//========================================================================================================
// Other Messages
//========================================================================================================
  $msg['msgRemoveDir']  = "למחוק את התיקיה הזו לצמיתות?";
  $msg['msgDeleteFile'] = "למחוק את הקובץ לצמיתות?";
  $msg['msgSaveFile']   = "לשמור ולמחוק את הקובץ הנוכחי?";

//========================================================================================================

?>