<?php

/**
 * This code is part of the FileManager software (www.gerd-tentler.de/tools/filemanager), copyright by
 * Gerd Tentler. Obtain permission before selling this code or hosting it on a commercial website or
 * redistributing it over the Internet or in any other medium. In all cases copyright must remain intact.
 */

//========================================================================================================
// General
//========================================================================================================
  $msg['fileInfo']      = "Informaчѕes do ficheiro";
  $msg['name']          = "Nome";
  $msg['size']          = "Tamanho";
  $msg['lastChange']    = "кltima modificaчуo";
  $msg['owner']         = "Proprietсrio";
  $msg['group']         = "Grupo";
  $msg['other']         = "Outros";
  $msg['read']          = "Lъr";
  $msg['write']         = "Escrever";
  $msg['execute']       = "Executar";
  $msg['permissions']   = "Permissѕes";
  $msg['error']         = "ERRO";
  $msg['searchResult']  = "Search Result";

//========================================================================================================
// Commands
//========================================================================================================
  $msg['cmdReset']      = "Anular";
  $msg['cmdSave']       = "Guardar";
  $msg['cmdViewList']   = "Vъr lista";
  $msg['cmdGetFile']    = "Obter ficheiro";
  $msg['cmdRename']     = "Alterar nome";
  $msg['cmdDelete']     = "Apagar";
  $msg['cmdEdit']       = "Editar";
  $msg['cmdChangePerm'] = "Alterar permissѕes";
  $msg['cmdFileInfo']   = "Vъr informaчѕes do ficheiro";
  $msg['cmdUploadFile'] = "Enviar ficheiro";
  $msg['cmdChangeDir']  = "Mudar directoria";
  $msg['cmdParentDir']  = "Directoria ligada";
  $msg['cmdNewDir']     = "Nova directoria";
  $msg['cmdSortAsc']    = "Ordenaчуo ascendente";
  $msg['cmdSortDesc']   = "Ordenaчуo descendente";
  $msg['cmdDetails']    = "View Details";
  $msg['cmdIcons']      = "View Icons";
  $msg['cmdSearch']     = "Search";
  $msg['cmdGoBack']     = "Go Back";
  $msg['cmdRefresh']    = "Refresh";
  $msg['cmdLogin']		  = "Login";

//========================================================================================================
// Error Messages
//========================================================================================================
  $msg['errPermChange'] = "Nуo щ possэvel alterar as permissѕes";
  $msg['errDirNew']     = "Erro ao criar";
  $msg['errOpen']       = "Erro ao abrir";
  $msg['errSave']       = "Erro ao salvar";
  $msg['errDelete']     = "Erro ao apagar";
  $msg['errRename']     = "Erro ao alterar o nome";
  $msg['errDisabled']   = "Funчуo desactivada pela administraчуo";
  $msg['errConnect']    = "Sem ligaчуo FTP ao servidor";
  $msg['errLogin']      = "Falha ao entrar";
  $msg['errAccess']     = "Access denied";

//========================================================================================================
// Other Messages
//========================================================================================================
  $msg['msgRemoveDir']  = "Deseja mesmo remover esta directoria? Nуo щ possэvel voltar atrсs!";
  $msg['msgDeleteFile'] = "Deseja mesmo apagar este ficheiro? Nуo serс possэvel voltar atrсs!";
  $msg['msgSaveFile']   = "Deseja salvar este ficheiro e substituir o actual?";

//========================================================================================================

?>