<?php

/**
 * This code is part of the FileManager software (www.gerd-tentler.de/tools/filemanager), copyright by
 * Gerd Tentler. Obtain permission before selling this code or hosting it on a commercial website or
 * redistributing it over the Internet or in any other medium. In all cases copyright must remain intact.
 */

//========================================================================================================
// General
//========================================================================================================
  $msg['fileInfo']      = "File Info";
  $msg['name']          = "Name";
  $msg['size']          = "Size";
  $msg['lastChange']    = "Last Change";
  $msg['owner']         = "Owner";
  $msg['group']         = "Group";
  $msg['other']         = "Other";
  $msg['read']          = "Read";
  $msg['write']         = "Write";
  $msg['execute']       = "Execute";
  $msg['permissions']   = "Permissions";
  $msg['error']         = "ERROR";
  $msg['searchResult']  = "Search Result";

//========================================================================================================
// Commands
//========================================================================================================
  $msg['cmdReset']      = "Reset";
  $msg['cmdSave']       = "Save";
  $msg['cmdViewList']   = "View List";
  $msg['cmdGetFile']    = "Get File";
  $msg['cmdRename']     = "Rename";
  $msg['cmdDelete']     = "Delete";
  $msg['cmdEdit']       = "Edit";
  $msg['cmdChangePerm'] = "Change Permissions";
  $msg['cmdFileInfo']   = "View File Info";
  $msg['cmdUploadFile'] = "Upload File";
  $msg['cmdChangeDir']  = "Change Directory";
  $msg['cmdParentDir']  = "Parent Directory";
  $msg['cmdNewDir']     = "New Directory";
  $msg['cmdSortAsc']    = "Sort Ascending";
  $msg['cmdSortDesc']   = "Sort Descending";
  $msg['cmdDetails']    = "View Details";
  $msg['cmdIcons']      = "View Icons";
  $msg['cmdSearch']     = "Search";
  $msg['cmdGoBack']     = "Go Back";
  $msg['cmdRefresh']    = "Refresh";
  $msg['cmdLogin']		  = "Login";

//========================================================================================================
// Error Messages
//========================================================================================================
  $msg['errPermChange'] = "Could not change permissions";
  $msg['errDirNew']     = "Error while creating";
  $msg['errOpen']       = "Error while opening";
  $msg['errSave']       = "Error while saving";
  $msg['errDelete']     = "Error while deleting";
  $msg['errRename']     = "Error while renaming";
  $msg['errDisabled']   = "This function has been disabled";
  $msg['errConnect']    = "No connection to FTP server";
  $msg['errLogin']      = "Login failed";
  $msg['errAccess']     = "Access denied";

//========================================================================================================
// Other Messages
//========================================================================================================
  $msg['msgRemoveDir']  = "Remove this directory irreversibly?";
  $msg['msgDeleteFile'] = "Delete this file irreversibly?";
  $msg['msgSaveFile']   = "Save file and overwrite existing one?";

//========================================================================================================

?>