<?php

/**
 * This code is part of the FileManager software (www.gerd-tentler.de/tools/filemanager), copyright by
 * Gerd Tentler. Obtain permission before selling this code or hosting it on a commercial website or
 * redistributing it over the Internet or in any other medium. In all cases copyright must remain intact.
 */

//========================================================================================================
// General
//========================================================================================================
  $msg['fileInfo']      = "Faili Info";
  $msg['name']          = "Nimi";
  $msg['size']          = "Suurus";
  $msg['lastChange']    = "Viimati muudetud";
  $msg['owner']         = "Omanik";
  $msg['group']         = "Grupp";
  $msg['other']         = "Muu";
  $msg['read']          = "Loe";
  $msg['write']         = "Kirjuta";
  $msg['execute']       = "Käivita";
  $msg['permissions']   = "Õigused";
  $msg['error']         = "VIGA";
  $msg['searchResult']  = "Otsingu tulemus";

//========================================================================================================
// Commands
//========================================================================================================
  $msg['cmdReset']      = "Algseaded";
  $msg['cmdSave']       = "Salvesta";
  $msg['cmdViewList']   = "Vaata failide nimekirja";
  $msg['cmdGetFile']    = "Lae alla";
  $msg['cmdRename']     = "Nimeta ümber";
  $msg['cmdDelete']     = "Kustuta";
  $msg['cmdEdit']       = "Redigeeri";
  $msg['cmdChangePerm'] = "Muuda õigusi";
  $msg['cmdFileInfo']   = "Vaata Faili Infot";
  $msg['cmdUploadFile'] = "Lae Fail Üles";
  $msg['cmdChangeDir']  = "Sisene kausta";
  $msg['cmdParentDir']  = "Eelmine kaust";
  $msg['cmdNewDir']     = "Uus kaust";
  $msg['cmdSortAsc']    = "Sorteeri Kasvavas järjekorras";
  $msg['cmdSortDesc']   = "Sorteeri Kahanevasjärjekorras";
  $msg['cmdDetails']    = "Detailne vaade";
  $msg['cmdIcons']      = "Lihtne vaade";
  $msg['cmdSearch']     = "Otsi";
  $msg['cmdGoBack']     = "Mine tagasi";
  $msg['cmdRefresh']    = "Värskenda vaadet";
  $msg['cmdLogin']      = "Logi sisse";

//========================================================================================================
// Error Messages
//========================================================================================================
  $msg['errPermChange'] = "Õigusi ei saa muuta";
  $msg['errDirNew']     = "Viga loomisel";
  $msg['errOpen']       = "Viga avamisel";
  $msg['errSave']       = "Viga salvestamisel";
  $msg['errDelete']     = "Viga kustutamsiel";
  $msg['errRename']     = "Viga nime muutmisel";
  $msg['errDisabled']   = "See funktsioon on ajutiselt keelatud";
  $msg['errConnect']    = "FTP serverile ligipääs puudub";
  $msg['errLogin']      = "Sisse logimine ebaõnnestus";
  $msg['errAccess']     = "Ligipääs keelatud";

//========================================================================================================
// Other Messages
//========================================================================================================
  $msg['msgRemoveDir']  = "Eemalda see kaust jäädavalt?";
  $msg['msgDeleteFile'] = "Kustuta see fail jäädavalt?";
  $msg['msgSaveFile']   = "Salvesta ja kirjuta olemasolev üle?";

//========================================================================================================

?>