<?php

/**
 * This code is part of the FileManager software (www.gerd-tentler.de/tools/filemanager), copyright by
 * Gerd Tentler. Obtain permission before selling this code or hosting it on a commercial website or
 * redistributing it over the Internet or in any other medium. In all cases copyright must remain intact.
 */

 /* Finnish tranlation by Mikael Lindeberg */

//========================================================================================================
// General
//========================================================================================================
  $msg['fileInfo']      = "Tiedosto Info";
  $msg['name']          = "Nimi";
  $msg['size']          = "Koko";
  $msg['lastChange']    = "Viimeksi muokattu";
  $msg['owner']         = "Omistaja";
  $msg['group']         = "Ryhmä";
  $msg['other']         = "Muu";
  $msg['read']          = "Lue";
  $msg['write']         = "Kirjoita";
  $msg['execute']       = "Suorita";
  $msg['permissions']   = "Oikeudet";
  $msg['error']         = "VIRHE";
  $msg['searchResult']  = "Hakutulokset";

//========================================================================================================
// Commands
//========================================================================================================
  $msg['cmdReset']      = "Resetoi";
  $msg['cmdSave']       = "Tallenna";
  $msg['cmdViewList']   = "Katso listaus";
  $msg['cmdGetFile']    = "Lataa tiedosto";
  $msg['cmdRename']     = "Uudelleen nimeä";
  $msg['cmdDelete']     = "Poista";
  $msg['cmdEdit']       = "Editoi";
  $msg['cmdChangePerm'] = "Muuta oikeuksia";
  $msg['cmdFileInfo']   = "Katso tiedoston tiedot";
  $msg['cmdUploadFile'] = "Siirrä tiedosto palvelimelle";
  $msg['cmdChangeDir']  = "Muuta kansiota";
  $msg['cmdParentDir']  = "Ylempi kansio";
  $msg['cmdNewDir']     = "Uusi Kansio";
  $msg['cmdSortAsc']    = "Lajittele nousevasti";
  $msg['cmdSortDesc']   = "Lajittele laskevasti";
  $msg['cmdDetails']    = "Listanäkymä";
  $msg['cmdIcons']      = "Ikoninäkymä";
  $msg['cmdSearch']     = "Haku";
  $msg['cmdGoBack']     = "Takaisin";
  $msg['cmdRefresh']    = "Päivitä";
  $msg['cmdLogin']		  = "Login";

//========================================================================================================
// Error Messages
//========================================================================================================
  $msg['errPermChange'] = "Oikeuksien muutos epäonnistui";
  $msg['errDirNew']     = "Uuden kansion luominen epäonnistui";
  $msg['errOpen']       = "Avaaminen epäonnistui";
  $msg['errSave']       = "Tallennus epäonnistui";
  $msg['errDelete']     = "Poisto epäonnistui";
  $msg['errRename']     = "Uudelleennimeäminen epäonnistui";
  $msg['errDisabled']   = "Tämä toiminto ei ole käytössä";
  $msg['errConnect']    = "Ei yhteyttä FTP palvelimeen";
  $msg['errLogin']      = "Kirjautuminen epäonnistui";
  $msg['errAccess']     = "Pääsy kielletty";

//========================================================================================================
// Other Messages
//========================================================================================================
  $msg['msgRemoveDir']  = "Poista tämä kansio lopullisesti?";
  $msg['msgDeleteFile'] = "Poista tämä tiedosto lopullisesti?";
  $msg['msgSaveFile']   = "Tallenna tiedosto vanhan päälle?";

//========================================================================================================

?>