all_carriers = [

  {
    "country": "Австрия",
    "carrier": "Hutchinson",
    "id":      "278",
    "phones": [
     {"phone": "0930399999",
      "fee": "2.49",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Австрия",
    "carrier": "Mobilkom",
    "id":      "274",
    "phones": [
     {"phone": "0930399999",
      "fee": "2.49",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Австрия",
    "carrier": "One",
    "id":      "276",
    "phones": [
     {"phone": "0930399999",
      "fee": "2.49",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Австрия",
    "carrier": "T-Mobile",
    "id":      "275",
    "phones": [
     {"phone": "0930399999",
      "fee": "2.49",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Австрия",
    "carrier": "Tele2",
    "id":      "279",
    "phones": [
     {"phone": "0930399999",
      "fee": "2.49",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Австрия",
    "carrier": "Telering",
    "id":      "277",
    "phones": [
     {"phone": "0930399999",
      "fee": "2.49",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Азербайджан",
    "carrier": "Azercell",
    "id":      "298",
    "phones": [
     {"phone": "9012",
      "fee": "1.4",
      "fee_curr": "USD"},
     {"phone": "9013",
      "fee": "3.6",
      "fee_curr": "USD"},
     {"phone": "9014",
      "fee": "6",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Армения",
    "carrier": "Armentel",
    "id":      "299",
    "phones": [
     {"phone": "1121",
      "fee": "0",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "200",
      "fee_curr": "AMD"},
     {"phone": "1151",
      "fee": "333.32",
      "fee_curr": "AMD"},
     {"phone": "1161",
      "fee": "1000",
      "fee_curr": "AMD"},
     {"phone": "1171",
      "fee": "1416.61",
      "fee_curr": "AMD"}
    ]
  },
  {
    "country": "Армения",
    "carrier": "Vivacell",
    "id":      "300",
    "phones": [
     {"phone": "1121",
      "fee": "0",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "200",
      "fee_curr": "AMD"},
     {"phone": "1151",
      "fee": "333.32",
      "fee_curr": "AMD"},
     {"phone": "1161",
      "fee": "1000",
      "fee_curr": "AMD"},
     {"phone": "1171",
      "fee": "1416.61",
      "fee_curr": "AMD"}
    ]
  },
  {
    "country": "Беларусь",
    "carrier": "БелСел",
    "id":      "200",
    "phones": [
     {"phone": "5014",
      "fee": "4.2",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Беларусь",
    "carrier": "МТС",
    "id":      "199",
    "phones": [
     {"phone": "5013",
      "fee": "3",
      "fee_curr": "USD"},
     {"phone": "5014",
      "fee": "4.2",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Бельгия",
    "carrier": "Base",
    "id":      "288",
    "phones": [
     {"phone": "7796",
      "fee": "2.5",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Бельгия",
    "carrier": "Mobistar",
    "id":      "289",
    "phones": [
     {"phone": "7796",
      "fee": "2.5",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Бельгия",
    "carrier": "Proximus",
    "id":      "290",
    "phones": [
     {"phone": "7796",
      "fee": "2.5",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Великобритания",
    "carrier": "O2",
    "id":      "232",
    "phones": [
     {"phone": "69067",
      "fee": "3.4",
      "fee_curr": "USD"},
     {"phone": "79067",
      "fee": "8.5",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Великобритания",
    "carrier": "Orange",
    "id":      "233",
    "phones": [
     {"phone": "69067",
      "fee": "3.4",
      "fee_curr": "USD"},
     {"phone": "79067",
      "fee": "8.5",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Великобритания",
    "carrier": "T-Mobile/Virgin",
    "id":      "234",
    "phones": [
     {"phone": "69067",
      "fee": "3.4",
      "fee_curr": "USD"},
     {"phone": "79067",
      "fee": "8.5",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Великобритания",
    "carrier": "Three",
    "id":      "235",
    "phones": [
     {"phone": "69067",
      "fee": "3.4",
      "fee_curr": "USD"},
     {"phone": "79067",
      "fee": "8.5",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Великобритания",
    "carrier": "Vodafone",
    "id":      "231",
    "phones": [
     {"phone": "69067",
      "fee": "3.4",
      "fee_curr": "USD"},
     {"phone": "79067",
      "fee": "8.5",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Венгрия",
    "carrier": "Pannon",
    "id":      "287",
    "phones": [
     {"phone": "90645045",
      "fee": "3.6",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Венгрия",
    "carrier": "T-Mobile",
    "id":      "291",
    "phones": [
     {"phone": "90645045",
      "fee": "3.6",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Венгрия",
    "carrier": "Vodafone",
    "id":      "292",
    "phones": [
     {"phone": "90645045",
      "fee": "3.6",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Германия",
    "carrier": "E-Plus",
    "id":      "244",
    "phones": [
     {"phone": "44442",
      "fee": "1",
      "fee_curr": "USD"},
     {"phone": "80888",
      "fee": "2.6",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Германия",
    "carrier": "Mobilcom",
    "id":      "247",
    "phones": [
     {"phone": "44442",
      "fee": "1",
      "fee_curr": "USD"},
     {"phone": "80888",
      "fee": "2.6",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Германия",
    "carrier": "O2",
    "id":      "245",
    "phones": [
     {"phone": "44442",
      "fee": "1",
      "fee_curr": "USD"},
     {"phone": "80888",
      "fee": "2.6",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Германия",
    "carrier": "Phonehouse",
    "id":      "259",
    "phones": [
     {"phone": "44442",
      "fee": "1",
      "fee_curr": "USD"},
     {"phone": "80888",
      "fee": "2.6",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Германия",
    "carrier": "T-Mobile",
    "id":      "242",
    "phones": [
     {"phone": "44442",
      "fee": "1",
      "fee_curr": "USD"},
     {"phone": "80888",
      "fee": "2.6",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Германия",
    "carrier": "Vodafone",
    "id":      "243",
    "phones": [
     {"phone": "44442",
      "fee": "1",
      "fee_curr": "USD"},
     {"phone": "80888",
      "fee": "2.6",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Германия",
    "carrier": "debitel",
    "id":      "246",
    "phones": [
     {"phone": "44442",
      "fee": "1",
      "fee_curr": "USD"},
     {"phone": "80888",
      "fee": "2.6",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Голландия",
    "carrier": "KPN",
    "id":      "236",
    "phones": [
     {"phone": "7117",
      "fee": "2",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Голландия",
    "carrier": "Orange",
    "id":      "239",
    "phones": [
     {"phone": "7117",
      "fee": "2",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Голландия",
    "carrier": "T-Mobile",
    "id":      "237",
    "phones": [
     {"phone": "7117",
      "fee": "2",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Голландия",
    "carrier": "Tele2",
    "id":      "241",
    "phones": [
     {"phone": "7117",
      "fee": "2",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Голландия",
    "carrier": "Telfort",
    "id":      "240",
    "phones": [
     {"phone": "7117",
      "fee": "2",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Голландия",
    "carrier": "Vodafone",
    "id":      "238",
    "phones": [
     {"phone": "7117",
      "fee": "2",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Израиль",
    "carrier": "Израиль",
    "id":      "258",
    "phones": [
     {"phone": "4545",
      "fee": "2.5",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Испания",
    "carrier": "Euskaltel",
    "id":      "255",
    "phones": [
     {"phone": "5339",
      "fee": "1.9",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Испания",
    "carrier": "Movistar",
    "id":      "251",
    "phones": [
     {"phone": "5339",
      "fee": "1.9",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Испания",
    "carrier": "Orange",
    "id":      "253",
    "phones": [
     {"phone": "5339",
      "fee": "1.9",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Испания",
    "carrier": "R",
    "id":      "256",
    "phones": [
     {"phone": "5339",
      "fee": "1.9",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Испания",
    "carrier": "Telecable",
    "id":      "257",
    "phones": [
     {"phone": "5339",
      "fee": "1.9",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Испания",
    "carrier": "Vodafone",
    "id":      "252",
    "phones": [
     {"phone": "5339",
      "fee": "1.9",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Испания",
    "carrier": "Yoigo",
    "id":      "254",
    "phones": [
     {"phone": "5339",
      "fee": "1.9",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Казахстан",
    "carrier": "K-Cell",
    "id":      "197",
    "phones": [
     {"phone": "9912",
      "fee": "110.17",
      "fee_curr": "KZT"},
     {"phone": "9915",
      "fee": "466.1",
      "fee_curr": "KZT"},
     {"phone": "9916",
      "fee": "338.98",
      "fee_curr": "KZT"},
     {"phone": "9917",
      "fee": "241",
      "fee_curr": "KZT"}
    ]
  },
  {
    "country": "Казахстан",
    "carrier": "КарТел",
    "id":      "207",
    "phones": [
     {"phone": "9912",
      "fee": "110.17",
      "fee_curr": "KZT"},
     {"phone": "9915",
      "fee": "466.1",
      "fee_curr": "KZT"},
     {"phone": "9916",
      "fee": "338.98",
      "fee_curr": "KZT"},
     {"phone": "9917",
      "fee": "241",
      "fee_curr": "KZT"}
    ]
  },
  {
    "country": "Киргизия",
    "carrier": "Бител",
    "id":      "153",
    "phones": [
     {"phone": "1131",
      "fee": "0.3",
      "fee_curr": "USD"},
     {"phone": "1141",
      "fee": "0.6",
      "fee_curr": "USD"},
     {"phone": "1151",
      "fee": "1",
      "fee_curr": "USD"},
     {"phone": "1161",
      "fee": "3",
      "fee_curr": "USD"},
     {"phone": "1171",
      "fee": "4.75",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Киргизия",
    "carrier": "МегаКом",
    "id":      "154",
    "phones": [
     {"phone": "1131",
      "fee": "0.3",
      "fee_curr": "USD"},
     {"phone": "1141",
      "fee": "0.6",
      "fee_curr": "USD"},
     {"phone": "1151",
      "fee": "1",
      "fee_curr": "USD"},
     {"phone": "1161",
      "fee": "3",
      "fee_curr": "USD"},
     {"phone": "1171",
      "fee": "4.75",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Латвия",
    "carrier": "Lmt",
    "id":      "167",
    "phones": [
     {"phone": "1871",
      "fee": "0.6",
      "fee_curr": "USD"},
     {"phone": "1872",
      "fee": "1",
      "fee_curr": "USD"},
     {"phone": "1873",
      "fee": "3.6",
      "fee_curr": "USD"},
     {"phone": "1874",
      "fee": "5.3",
      "fee_curr": "USD"},
     {"phone": "29301199:300",
      "fee": "3",
      "fee_curr": "LVL"}
    ]
  },
  {
    "country": "Латвия",
    "carrier": "Tele-2",
    "id":      "168",
    "phones": [
     {"phone": "1871",
      "fee": "0.6",
      "fee_curr": "USD"},
     {"phone": "1872",
      "fee": "1",
      "fee_curr": "USD"},
     {"phone": "1873",
      "fee": "3.6",
      "fee_curr": "USD"},
     {"phone": "1874",
      "fee": "5.3",
      "fee_curr": "USD"},
     {"phone": "26000613:300",
      "fee": "3",
      "fee_curr": "LVL"}
    ]
  },
  {
    "country": "Литва",
    "carrier": "Bite",
    "id":      "163",
    "phones": [
     {"phone": "1381",
      "fee": "0.33",
      "fee_curr": "USD"},
     {"phone": "1390:1000",
      "fee": "10",
      "fee_curr": "LTL"},
     {"phone": "1391",
      "fee": "1.17",
      "fee_curr": "USD"},
     {"phone": "1635",
      "fee": "2.83",
      "fee_curr": "USD"},
     {"phone": "1645",
      "fee": "4.21",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Литва",
    "carrier": "Omnitel",
    "id":      "164",
    "phones": [
     {"phone": "1381",
      "fee": "0.41",
      "fee_curr": "USD"},
     {"phone": "1390:1000",
      "fee": "10",
      "fee_curr": "LTL"},
     {"phone": "1391",
      "fee": "1.24",
      "fee_curr": "USD"},
     {"phone": "1635",
      "fee": "2.89",
      "fee_curr": "USD"},
     {"phone": "1645",
      "fee": "4.12",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Литва",
    "carrier": "Tele-2",
    "id":      "166",
    "phones": [
     {"phone": "1381",
      "fee": "0.41",
      "fee_curr": "USD"},
     {"phone": "1390:1000",
      "fee": "10",
      "fee_curr": "LTL"},
     {"phone": "1391",
      "fee": "1.24",
      "fee_curr": "USD"},
     {"phone": "1635",
      "fee": "3.3",
      "fee_curr": "USD"},
     {"phone": "1645",
      "fee": "4.12",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Норвегия",
    "carrier": "NetCom",
    "id":      "228",
    "phones": [
     {"phone": "2322",
      "fee": "3.1",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Норвегия",
    "carrier": "Tele2",
    "id":      "230",
    "phones": [
     {"phone": "2322",
      "fee": "3.1",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Норвегия",
    "carrier": "Telenor",
    "id":      "227",
    "phones": [
     {"phone": "2322",
      "fee": "3.1",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Норвегия",
    "carrier": "Ventelo",
    "id":      "229",
    "phones": [
     {"phone": "2322",
      "fee": "3.1",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Польша",
    "carrier": "Era",
    "id":      "267",
    "phones": [
     {"phone": "7910",
      "fee": "4",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Польша",
    "carrier": "Orange",
    "id":      "265",
    "phones": [
     {"phone": "7910",
      "fee": "4",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Польша",
    "carrier": "Play",
    "id":      "268",
    "phones": [
     {"phone": "7910",
      "fee": "4",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Польша",
    "carrier": "Plus",
    "id":      "266",
    "phones": [
     {"phone": "7910",
      "fee": "4",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Португалия",
    "carrier": "Optimus",
    "id":      "250",
    "phones": [
     {"phone": "4565",
      "fee": "2.6",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Португалия",
    "carrier": "TMN",
    "id":      "248",
    "phones": [
     {"phone": "4565",
      "fee": "2.6",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Португалия",
    "carrier": "Vodafone",
    "id":      "249",
    "phones": [
     {"phone": "4565",
      "fee": "2.6",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "TELE2",
    "id":      "107",
    "phones": [
     {"phone": "1121",
      "fee": "3",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "9",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "18",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "29.7",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "89.7",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "168",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "71",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "228.82",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "92.37",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.07",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "UTEL",
    "id":      "106",
    "phones": [
     {"phone": "1121",
      "fee": "3",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "9",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "18",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "30",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "90",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "150",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "60",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "260",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "90",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "150",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "АКОС",
    "id":      "158",
    "phones": [
     {"phone": "1121",
      "fee": "3",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "9",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "18",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "29.7",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "90.8",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "143.8",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "60.6",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "228.82",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "92.37",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.07",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "БайкалВестКом",
    "id":      "122",
    "phones": [
     {"phone": "1121",
      "fee": "3",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "11.86",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "22.42",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "34.22",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "105.02",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "168.15",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "70.8",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "338.98",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "92.37",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.07",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "Билайн",
    "id":      "120",
    "phones": [
     {"phone": "1121",
      "fee": "2.97",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "12.71",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "23.73",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "33.9",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "94.07",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "144.07",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "59.32",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "254.24",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "94.07",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.07",
      "fee_curr": "RUR"},
     {"phone": "840501",
      "fee": "42",
      "fee_curr": "RUR"},
     {"phone": "840502",
      "fee": "84",
      "fee_curr": "RUR"},
     {"phone": "840503",
      "fee": "169",
      "fee_curr": "RUR"},
     {"phone": "840504",
      "fee": "423",
      "fee_curr": "RUR"},
     {"phone": "840511",
      "fee": "84",
      "fee_curr": "RUR"},
     {"phone": "840512",
      "fee": "169",
      "fee_curr": "RUR"},
     {"phone": "840513",
      "fee": "423",
      "fee_curr": "RUR"},
     {"phone": "840514",
      "fee": "847",
      "fee_curr": "RUR"},
     {"phone": "840521",
      "fee": "900",
      "fee_curr": "RUR"},
     {"phone": "840522",
      "fee": "3000",
      "fee_curr": "RUR"},
     {"phone": "840531",
      "fee": "1500",
      "fee_curr": "RUR"},
     {"phone": "840532",
      "fee": "1200",
      "fee_curr": "RUR"},
     {"phone": "845021",
      "fee": "338",
      "fee_curr": "RUR"},
     {"phone": "845022",
      "fee": "677",
      "fee_curr": "RUR"},
     {"phone": "845023",
      "fee": "1016",
      "fee_curr": "RUR"},
     {"phone": "845024",
      "fee": "1271",
      "fee_curr": "RUR"},
     {"phone": "845031",
      "fee": "254",
      "fee_curr": "RUR"},
     {"phone": "845032",
      "fee": "508",
      "fee_curr": "RUR"},
     {"phone": "845033",
      "fee": "762",
      "fee_curr": "RUR"},
     {"phone": "845034",
      "fee": "1016",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "Дельта Телеком",
    "id":      "156",
    "phones": [
     {"phone": "1121",
      "fee": "3",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "9",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "18",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "30",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "90",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "150",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "60",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "300",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "92",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "Енисей Телеком",
    "id":      "184",
    "phones": [
     {"phone": "1121",
      "fee": "3",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "9",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "18",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "30",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "90",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "140",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "60",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "228.81",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "92.37",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.07",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "МОТИВ",
    "id":      "115",
    "phones": [
     {"phone": "1121",
      "fee": "3.05",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "11.8",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "22.5",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "34.25",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "105",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "169.33",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "69.7",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "228.82",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "92.37",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.07",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "МТС",
    "id":      "105",
    "phones": [
     {"phone": "1121",
      "fee": "2.87",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "8.61",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "17.22",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "28.41",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "85.81",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "157.85",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "57.4",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "258.3",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "94.71",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "157.85",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "МТС - МР Дальневосточный",
    "id":      "175",
    "phones": [
     {"phone": "1121",
      "fee": "2.87",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "8.61",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "17.22",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "28.41",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "85.81",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "157.85",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "57.4",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "258.3",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "94.71",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "157.85",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "МТС - МР Приволжский",
    "id":      "180",
    "phones": [
     {"phone": "1121",
      "fee": "2.87",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "8.61",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "17.22",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "28.41",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "85.81",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "157.85",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "57.4",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "258.3",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "94.71",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "157.85",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "МТС - МР Северо-Западный",
    "id":      "178",
    "phones": [
     {"phone": "1121",
      "fee": "2.87",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "8.61",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "17.22",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "28.41",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "85.81",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "157.85",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "57.4",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "258.3",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "94.71",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "157.85",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "МТС - МР Северо-кавказский",
    "id":      "181",
    "phones": [
     {"phone": "1121",
      "fee": "2.87",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "8.61",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "17.22",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "28.41",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "85.81",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "157.85",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "57.4",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "258.3",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "94.71",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "157.85",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "МТС - МР Сибирский",
    "id":      "179",
    "phones": [
     {"phone": "1121",
      "fee": "2.87",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "8.61",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "17.22",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "28.41",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "85.81",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "157.85",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "57.4",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "258.3",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "94.71",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "157.85",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "МТС - МР Уральский",
    "id":      "177",
    "phones": [
     {"phone": "1121",
      "fee": "2.87",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "8.61",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "17.22",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "28.41",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "85.81",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "157.85",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "57.4",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "258.3",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "94.71",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "157.85",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "МТС - МР Центральный",
    "id":      "176",
    "phones": [
     {"phone": "1121",
      "fee": "2.87",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "8.61",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "17.22",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "28.41",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "85.81",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "157.85",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "57.4",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "258.3",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "94.71",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "157.85",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "МТС - Москва",
    "id":      "138",
    "phones": [
     {"phone": "1121",
      "fee": "2.87",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "8.61",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "17.22",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "28.41",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "85.81",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "157.85",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "57.4",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "258.3",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "94.71",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "157.85",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "МТС - РеКом",
    "id":      "128",
    "phones": [
     {"phone": "1121",
      "fee": "2.87",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "10",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "17.22",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "28.41",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "85.81",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "157.85",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "57.4",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "258.3",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "94.71",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "157.85",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "Мегафон - Дальний Восток",
    "id":      "113",
    "phones": [
     {"phone": "1121",
      "fee": "3",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "10",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "19",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "29.7",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "119",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "150",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "89",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "150",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "99",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.06",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "Мегафон - Москва",
    "id":      "112",
    "phones": [
     {"phone": "1121",
      "fee": "3",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "10",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "19",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "29.7",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "119",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "150",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "89",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "150",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "99",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.06",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "Мегафон - Поволжье",
    "id":      "110",
    "phones": [
     {"phone": "1121",
      "fee": "3",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "10",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "19",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "29.7",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "119",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "150",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "89",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "150",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "99",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.06",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "Мегафон - Северный Кавказ",
    "id":      "109",
    "phones": [
     {"phone": "1121",
      "fee": "3",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "10",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "19",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "29.7",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "119",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "150",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "89",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "150",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "99",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.06",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "Мегафон - Северо-Запад",
    "id":      "116",
    "phones": [
     {"phone": "1121",
      "fee": "3",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "10",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "19",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "29.7",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "119",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "150",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "89",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "150",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "99",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.06",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "Мегафон - Сибирь",
    "id":      "121",
    "phones": [
     {"phone": "1121",
      "fee": "3",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "10",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "19",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "29.7",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "119",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "150",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "89",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "150",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "99",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.06",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "Мегафон - Урал",
    "id":      "119",
    "phones": [
     {"phone": "1121",
      "fee": "3",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "10",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "19",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "29.7",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "119",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "150",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "89",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "150",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "99",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.06",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "Мегафон - Центр",
    "id":      "127",
    "phones": [
     {"phone": "1121",
      "fee": "3",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "10",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "19",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "29.7",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "119",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "150",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "89",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "150",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "99",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.06",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "Мегафон - Центр - Северный филиал",
    "id":      "137",
    "phones": [
     {"phone": "1121",
      "fee": "3",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "10",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "19",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "29.7",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "119",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "150",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "89",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "150",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "99",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.06",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "Мегафон - Центр - Южный филиал",
    "id":      "133",
    "phones": [
     {"phone": "1121",
      "fee": "3",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "10",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "19",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "29.7",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "119",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "150",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "89",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "150",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "99",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.06",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "НСС",
    "id":      "281",
    "phones": [
     {"phone": "1121",
      "fee": "2.85",
      "fee_curr": "RUR7"},
     {"phone": "1131",
      "fee": "8.43",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "19.68",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "27.84",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "84.36",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "112.48",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "56.24",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "112",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "НСС - Нижний Новгород",
    "id":      "118",
    "phones": [
     {"phone": "1121",
      "fee": "2.85",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "8.43",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "19.68",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "27.84",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "84.36",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "112.48",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "66.36",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "112.48",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "98.42",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "112.48",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "НТК",
    "id":      "126",
    "phones": [
     {"phone": "1121",
      "fee": "2.9",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "8.7",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "17.4",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "28.71",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "86.71",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "137.75",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "58",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "260",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "86.71",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "145",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "Оренбург GSM",
    "id":      "104",
    "phones": [
     {"phone": "1121",
      "fee": "2.54",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "11",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "22",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "34.22",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "76.28",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "169.33",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "5",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "228.82",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "92.37",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.07",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "СМАРТС - Астрахань",
    "id":      "140",
    "phones": [
     {"phone": "1121",
      "fee": "3",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "12",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "22",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "34.22",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "124",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "200",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "69.62",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "254.24",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "93.22",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.07",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "СМАРТС - Волгоград GSM",
    "id":      "125",
    "phones": [
     {"phone": "1121",
      "fee": "3",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "11.8",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "22.42",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "34.22",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "90",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "140",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "69.62",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "101.69",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "90",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "90",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "СМАРТС - Иваново",
    "id":      "145",
    "phones": [
     {"phone": "1121",
      "fee": "2.97",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "8.47",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "17.8",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "29.66",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "120.34",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "144.07",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "71.19",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "254.24",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "92.37",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.07",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "СМАРТС - Пенза",
    "id":      "162",
    "phones": [
     {"phone": "1121",
      "fee": "2.97",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "8.47",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "21.17",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "29.66",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "123.73",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "144.07",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "69.49",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "169.49",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "93.22",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.07",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "СМАРТС - Самара",
    "id":      "141",
    "phones": [
     {"phone": "1121",
      "fee": "2.97",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "8.47",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "17.8",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "29.66",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "144.07",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "144.07",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "71.19",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "254.24",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "93.22",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.07",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "СМАРТС - Шупашкар",
    "id":      "148",
    "phones": [
     {"phone": "1121",
      "fee": "2.97",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "11",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "22",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "34.22",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "107",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "170",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "61.02",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "254.24",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "93.22",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.07",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "СМАРТС - Ярославль",
    "id":      "203",
    "phones": [
     {"phone": "1121",
      "fee": "2.97",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "8.47",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "17.8",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "29.66",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "124",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "144.07",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "69.62",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "254.24",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "93.22",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.07",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "СТеК Джи Эс Эм",
    "id":      "143",
    "phones": [
     {"phone": "1121",
      "fee": "3",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "12",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "18",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "30",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "106",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "170",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "70",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "228.82",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "92.37",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.07",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "Саратов-Мобайл",
    "id":      "186",
    "phones": [
     {"phone": "1121",
      "fee": "2.42",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "7.15",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "14.14",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "23.62",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "71.49",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "107.73",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "2",
      "fee_curr": "USD"},
     {"phone": "3649",
      "fee": "179.54",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "83.41",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "95.32",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "Татинком",
    "id":      "264",
    "phones": [
     {"phone": "1121",
      "fee": "2.86",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "8.43",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "19.68",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "27.84",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "84.36",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "112.47",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "56.24",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "112.48",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "Ульяновск GSM",
    "id":      "161",
    "phones": [
     {"phone": "1121",
      "fee": "2.97",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "11",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "22",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "34",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "89.83",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "170",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "71",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "254.24",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "92.37",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.07",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Россия",
    "carrier": "Цифровая экспансия",
    "id":      "129",
    "phones": [
     {"phone": "1121",
      "fee": "2.97",
      "fee_curr": "RUR"},
     {"phone": "1131",
      "fee": "8.47",
      "fee_curr": "RUR"},
     {"phone": "1141",
      "fee": "17.8",
      "fee_curr": "RUR"},
     {"phone": "1151",
      "fee": "29.66",
      "fee_curr": "RUR"},
     {"phone": "1161",
      "fee": "89.83",
      "fee_curr": "RUR"},
     {"phone": "1171",
      "fee": "144.07",
      "fee_curr": "RUR"},
     {"phone": "1899",
      "fee": "60",
      "fee_curr": "RUR"},
     {"phone": "3649",
      "fee": "254.24",
      "fee_curr": "RUR"},
     {"phone": "5013",
      "fee": "92.37",
      "fee_curr": "RUR"},
     {"phone": "5014",
      "fee": "144.07",
      "fee_curr": "RUR"}
    ]
  },
  {
    "country": "Таджикистан",
    "carrier": "MLT",
    "id":      "152",
    "phones": [
     {"phone": "1131",
      "fee": "0.3",
      "fee_curr": "USD"},
     {"phone": "1141",
      "fee": "0.6",
      "fee_curr": "USD"},
     {"phone": "1151",
      "fee": "1",
      "fee_curr": "USD"},
     {"phone": "1161",
      "fee": "3",
      "fee_curr": "USD"},
     {"phone": "1171",
      "fee": "4.75",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Таджикистан",
    "carrier": "Билайн",
    "id":      "270",
    "phones": [
     {"phone": "1131",
      "fee": "0.3",
      "fee_curr": "USD"},
     {"phone": "1141",
      "fee": "0.6",
      "fee_curr": "USD"},
     {"phone": "1151",
      "fee": "1",
      "fee_curr": "USD"},
     {"phone": "1161",
      "fee": "3",
      "fee_curr": "USD"},
     {"phone": "1171",
      "fee": "4.75",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Таджикистан",
    "carrier": "Вавилон-М",
    "id":      "214",
    "phones": [
     {"phone": "1131",
      "fee": "0.3",
      "fee_curr": "USD"},
     {"phone": "1141",
      "fee": "0.6",
      "fee_curr": "USD"},
     {"phone": "1151",
      "fee": "1",
      "fee_curr": "USD"},
     {"phone": "1161",
      "fee": "3",
      "fee_curr": "USD"},
     {"phone": "1171",
      "fee": "4.75",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Таджикистан",
    "carrier": "Индиго",
    "id":      "151",
    "phones": [
     {"phone": "1131",
      "fee": "0.3",
      "fee_curr": "USD"},
     {"phone": "1141",
      "fee": "0.6",
      "fee_curr": "USD"},
     {"phone": "1151",
      "fee": "1",
      "fee_curr": "USD"},
     {"phone": "1161",
      "fee": "3",
      "fee_curr": "USD"},
     {"phone": "1171",
      "fee": "4.75",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Украина",
    "carrier": "Life",
    "id":      "215",
    "phones": [
     {"phone": "1161",
      "fee": "18",
      "fee_curr": "UAH"},
     {"phone": "1171",
      "fee": "25",
      "fee_curr": "UAH"}
    ]
  },
  {
    "country": "Украина",
    "carrier": "UMC",
    "id":      "160",
    "phones": [
     {"phone": "5011",
      "fee": "1.69",
      "fee_curr": "UAH"},
     {"phone": "5012",
      "fee": "5",
      "fee_curr": "UAH"},
     {"phone": "5013",
      "fee": "15.25",
      "fee_curr": "UAH"},
     {"phone": "5014",
      "fee": "21.19",
      "fee_curr": "UAH"}
    ]
  },
  {
    "country": "Украина",
    "carrier": "Билайн",
    "id":      "216",
    "phones": [
     {"phone": "5011",
      "fee": "1.69",
      "fee_curr": "UAH"},
     {"phone": "5012",
      "fee": "5",
      "fee_curr": "UAH"},
     {"phone": "5013",
      "fee": "15.25",
      "fee_curr": "UAH"},
     {"phone": "5014",
      "fee": "21.19",
      "fee_curr": "UAH"}
    ]
  },
  {
    "country": "Украина",
    "carrier": "Киевстар",
    "id":      "159",
    "phones": [
     {"phone": "5011",
      "fee": "1.69",
      "fee_curr": "UAH"},
     {"phone": "5012",
      "fee": "5",
      "fee_curr": "UAH"},
     {"phone": "5013",
      "fee": "15.25",
      "fee_curr": "UAH"},
     {"phone": "5014",
      "fee": "21.19",
      "fee_curr": "UAH"}
    ]
  },
  {
    "country": "Финляндия",
    "carrier": "DNA",
    "id":      "218",
    "phones": [
     {"phone": "179479",
      "fee": "2.5",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Финляндия",
    "carrier": "Elisa",
    "id":      "219",
    "phones": [
     {"phone": "179479",
      "fee": "2.5",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Финляндия",
    "carrier": "Saunalahti",
    "id":      "220",
    "phones": [
     {"phone": "179479",
      "fee": "2.5",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Финляндия",
    "carrier": "Sonera",
    "id":      "217",
    "phones": [
     {"phone": "179479",
      "fee": "2.5",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Франция",
    "carrier": "Bouygues",
    "id":      "301",
    "phones": [
     {"phone": "83868",
      "fee": "3.8",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Франция",
    "carrier": "Orange",
    "id":      "302",
    "phones": [
     {"phone": "83868",
      "fee": "3.8",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Франция",
    "carrier": "Sfr",
    "id":      "303",
    "phones": [
     {"phone": "83868",
      "fee": "3.8",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Чехия",
    "carrier": "O2",
    "id":      "260",
    "phones": [
     {"phone": "9090150",
      "fee": "2.2",
      "fee_curr": "USD"},
     {"phone": "9090199",
      "fee": "4.35",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Чехия",
    "carrier": "T-Mobile",
    "id":      "261",
    "phones": [
     {"phone": "9090150",
      "fee": "2.2",
      "fee_curr": "USD"},
     {"phone": "9090199",
      "fee": "4.35",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Чехия",
    "carrier": "Vodafone",
    "id":      "262",
    "phones": [
     {"phone": "9090150",
      "fee": "2.2",
      "fee_curr": "USD"},
     {"phone": "9090199",
      "fee": "4.35",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Швеция",
    "carrier": "Tele2",
    "id":      "225",
    "phones": [
     {"phone": "72170",
      "fee": "2.6",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Швеция",
    "carrier": "Telenor",
    "id":      "223",
    "phones": [
     {"phone": "72170",
      "fee": "2.6",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Швеция",
    "carrier": "Telia",
    "id":      "222",
    "phones": [
     {"phone": "72170",
      "fee": "2.6",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Швеция",
    "carrier": "Tre",
    "id":      "224",
    "phones": [
     {"phone": "72170",
      "fee": "2.6",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Эстония",
    "carrier": "Elisa",
    "id":      "170",
    "phones": [
     {"phone": "13202:5000",
      "fee": "50",
      "fee_curr": "EEK"},
     {"phone": "17010",
      "fee": "0.4",
      "fee_curr": "USD"},
     {"phone": "17011",
      "fee": "1",
      "fee_curr": "USD"},
     {"phone": "17012",
      "fee": "2.6",
      "fee_curr": "USD"},
     {"phone": "17013",
      "fee": "3.5",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Эстония",
    "carrier": "Emt",
    "id":      "169",
    "phones": [
     {"phone": "13202:5000",
      "fee": "50",
      "fee_curr": "EEK"},
     {"phone": "17010",
      "fee": "0.4",
      "fee_curr": "USD"},
     {"phone": "17011",
      "fee": "1",
      "fee_curr": "USD"},
     {"phone": "17012",
      "fee": "2.6",
      "fee_curr": "USD"},
     {"phone": "17013",
      "fee": "3.5",
      "fee_curr": "USD"}
    ]
  },
  {
    "country": "Эстония",
    "carrier": "Tele-2",
    "id":      "172",
    "phones": [
     {"phone": "13202:5000",
      "fee": "50",
      "fee_curr": "EEK"},
     {"phone": "17010",
      "fee": "0.4",
      "fee_curr": "USD"},
     {"phone": "17011",
      "fee": "1",
      "fee_curr": "USD"},
     {"phone": "17012",
      "fee": "2.6",
      "fee_curr": "USD"},
     {"phone": "17013",
      "fee": "3.5",
      "fee_curr": "USD"}
    ]
  }
]
